name: http_hook
description: A lightweight and flexible Dart HTTP request interception and mocking library for testing and debugging. Supports precise URL matching, path template matching, regex matching, and dynamic response generation.
version: 0.0.1
homepage: https://github.com/drown0315/http_hook
issue_tracker: https://github.com/drown0315/http_hook/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  test: ^1.24.0

dev_dependencies:
  http: ^1.1.0

topics:
  - http
  - mock
  - testing
  - interceptor 